"""
Django settings for CryptoTradeProject__ project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p7#kko-m(=tm%pkp%2c(!*ma#1!-%&#q)04s4it4=nw-r9^x!w'

import os
from dotenv import load_dotenv

load_dotenv()
NOW_PAYMENT_API_KEY = os.getenv('NOWPAYMENT_API_KEY')
NOW_PAYMENT_IPN_KEY = os.getenv('NOWPAYMENT_IPN_KEY')
TRON_API_KEY = os.getenv('TRONGRID_API_KEY')
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"
FERNET_KEY = os.getenv("FERNET_KEY")
# DATABASE_URL = os.getenv("DATABASE_URL")

# SECURITY WARNING: don't run with debug turned on in production!
# noinspection PyRedeclaration
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'dashboard',
    'widget_tweaks',
    'wallet',
    'django.contrib.humanize',
    'adminPanel',
    'UserPanel',
    'Prediction',
    'channels',
    'template_partials',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # قبل از SessionMiddleware
    'adminPanel.middleware.AdminPanelCookieMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # بعد از SessionMiddleware
    'adminPanel.middleware.AdminLockScreenMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # 👇 مهم: AuthenticationMiddleware باید قبل از BanUserMiddleware باشد
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # حالا BanUserMiddleware را بعد از آن قرار می‌دهیم
    'UserPanel.middleware.BanUserMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'accounts.middleware.LockScreenMiddleware',  # lock کاربر عادی
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'adminPanel.backends.AdminUserBackend',  # ادمین جدا
    'django.contrib.auth.backends.ModelBackend',  # کاربران عادی
]

# settings.py
AUTH_USER_MODEL = "accounts.User"

ROOT_URLCONF = 'CryptoTradeProject__.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # 'APP_DIRS': True,  <-- این خط را حتماً کامنت کن یا حذف کن
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wallet.context_processor.breadcrumb_context',
                'wallet.context_processor.wallet_context',
                'dashboard.context_processors.notification_context',
                'dashboard.context_processors.twofa_status',
                'dashboard.context_processors.kyc_processor',
                'adminPanel.context_processors.admin_counters',
            ],
            # اضافه کردن لودر پارشیال برای شناسایی هشتگ (#) در Render
            'loaders': [
                ('django_template_partials.loader.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'CryptoTradeProject__.wsgi.application'
ASGI_APPLICATION = "CryptoTradeProject__.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            "capacity": 1500,  # 🚀 ظرفیت صف پیام‌ها را از 100 به 1500 افزایش می‌دهد تا پیام‌ها گم نشوند
            "expiry": 10,  # ⏳ پیام‌های قدیمی خوانده‌نشده بعد از 10 ثانیه حذف می‌شوند تا رم سرور پر نشود
        },
    },
}

STATIC_URL = '/static/'
# مسیر پوشه استاتیک پروژه (مثال)
print("Looking for static files in:", BASE_DIR / "static")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# مسیر ذخیره استاتیک‌های جمع شده
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crypto_db',  # نام دیتابیسی که در ترمینال ساختید
        'USER': 'myuser',  # نام کاربری ساخت شده
        'PASSWORD': 'mypassword',  # رمز عبور ست شده
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        },
    },
    'handlers': {
        'trading_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # تغییر به این کلاس
            'filename': os.path.join(BASE_DIR, 'logs/trading_activity.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,  # نگهداری ۵ فایل لاگ قدیمی
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'trading': {
            'handlers': ['trading_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'CryptoTradeProject__.validators.ComplexityValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'UTC'
USE_TZ = True

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mhmmdahmadi6@gmail.com"
EMAIL_HOST_PASSWORD = "wjzvurxunkgpjooo"
DEFAULT_FROM_EMAIL = "CryptoTrade <mhmmdahmadi6@gmail.com>"

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # یا آدرس Redis سرور
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_IGNORE_RESULT = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'max_retries': 5,
    'interval_start': 0,
    'interval_step': 0.5,
    'interval_max': 3,
}

ADMIN_SESSION_COOKIE = "admin_sessionid"

SESSION_COOKIE_AGE = 1800
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = False  # در سرور اصلی حتماً True شود
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True
CSRF_COOKIE_SECURE = False  # در سرور اصلی حتماً True شود
SESSION_COOKIE_SAMESITE = 'Lax'
LOGIN_URL = '/sign_in/'
LOGOUT_REDIRECT_URL = '/sign_in/'

CELERY_BEAT_SCHEDULE = {
    'activate-pending-rounds-task': {
        'task': 'Prediction.tasks.activate_pending_rounds',
        'schedule': 3.0,
    },
    'advance-timeframe-auto-task': {
        'task': 'Prediction.tasks.advance_timeframe_auto',
        'schedule': 5.0,
    },
    'settle-every-2-seconds': {
        'task': 'Prediction.tasks.settle_expired_predictions',
        'schedule': 2.0,  # اجرای مداوم هر ۲ ثانیه برای سرعت بالای تسویه حساب
    },
    'cleanup-invitations-every-midnight': {
        'task': 'adminPanel.tasks.cleanup_expired_invitations',
        'schedule': crontab(hour=0, minute=0),
    },
    'fetch-crypto-prices-every-30-seconds': {
        'task': 'nex_trade_fetch_live_prices',
        'schedule': 30.0,
    },
}

# 🚀 ساختار یکپارچه کش برای هماهنگی کامل با لایه وب‌ساکت، سلری و قیمت‌ها
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
