# Generated by Django 5.2.5 on 2025-12-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_adminwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
