# Generated by Django 6.0 on 2026-01-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediction', '0013_prediction_fee_amount'),
        ('adminPanel', '0004_alter_adminuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWalletJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='adminPanel.adminwallet')),
                ('prediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prediction.prediction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
