# Generated by Django 6.0 on 2026-01-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_adminwalletjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_wallet', to='adminPanel.adminuser'),
        ),
    ]
