# Generated by Django 6.0 on 2026-01-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediction', '0015_walletjournal_entry_price_walletjournal_fee_deducted_and_more'),
        ('adminPanel', '0006_alter_adminwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwalletjournal',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Email of the user who generated this fee', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adminwalletjournal',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prediction.prediction'),
        ),
    ]
