# Generated by Django 6.0 on 2026-01-31 16:14

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_adminwalletjournal_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
