# Generated by Django 6.0 on 2026-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0008_adminuser_is_otp_enabled_adminuser_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='otp_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
