# Generated by Django 6.0 on 2026-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_adminuser_date_joined_adminuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
