# Generated by Django 6.0 on 2026-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_alter_adminuser_username_admininvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(default='ddddd', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
