# Generated by Django 6.0 on 2026-02-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_alter_adminuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
    ]
