# Generated by Django 6.0 on 2026-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_adminuser_is_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='permissions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
