# Generated by Django 6.0 on 2026-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_admininvitation_permissions_adminuser_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
