# Generated by Django 6.0 on 2026-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('FAILED_LOGIN', 'failed_login')], max_length=20),
        ),
    ]
