# Generated by Django 6.0 on 2026-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_adminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchat',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to='adminPanel.adminuser'),
        ),
    ]
