# Generated by Django 6.0 on 2026-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_adminchat_hidden_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchat',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminchat',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_messages', to='adminPanel.adminuser'),
        ),
    ]
