# Generated by Django 6.0 on 2026-02-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_adminchat_is_edited_adminchat_seen_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminwallet',
            name='user',
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='title',
            field=models.CharField(default='Platform Treasury', max_length=50),
        ),
    ]
