# Generated by Django 6.0 on 2026-02-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0022_remove_adminwallet_user_adminwallet_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('destination_wallet', models.CharField(help_text='آدرس کیف پول تتر یا مقصد', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.adminuser')),
            ],
        ),
    ]
