# Generated by Django 6.0 on 2026-02-07 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prediction', '0015_walletjournal_entry_price_walletjournal_fee_deducted_and_more'),
        ('adminPanel', '0023_adminwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Platform Revenue Account', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminwalletjournal',
            name='admin_wallet',
        ),
        migrations.RemoveField(
            model_name='adminwalletjournal',
            name='prediction',
        ),
        migrations.AlterField(
            model_name='adminwithdrawal',
            name='destination_wallet',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RevenueJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='adminPanel.platformrevenue')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prediction.prediction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='AdminWallet',
        ),
        migrations.DeleteModel(
            name='AdminWalletJournal',
        ),
    ]
