# Generated by Django 6.0 on 2026-02-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0024_platformrevenue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminwithdrawal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adminwithdrawal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='adminPanel.adminuser'),
        ),
        migrations.AddField(
            model_name='adminwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminwithdrawal',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='adminPanel.adminuser'),
        ),
    ]
