# Generated by Django 6.0 on 2026-02-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0025_alter_adminwithdrawal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='sender',
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='admin_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.adminuser'),
        ),
    ]
