# Generated by Django 6.0 on 2026-02-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0026_remove_ticketreply_sender_ticketreply_admin_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='admin_sender',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='adminPanel.adminuser'),
            preserve_default=False,
        ),
    ]
