# Generated by Django 6.0 on 2026-02-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_alter_ticketreply_admin_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminChat',
        ),
    ]
