# Generated by Django 6.0 on 2026-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0028_delete_adminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='currency',
            field=models.CharField(default='usdttrc20', max_length=20, unique=True, verbose_name='currency code'),
        ),
    ]
