# Generated by Django 6.0 on 2026-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0029_platformrevenue_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuejournal',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
