# Generated by Django 6.0 on 2026-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0030_alter_revenuejournal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwithdrawal',
            name='currency',
            field=models.CharField(default='usdttrc20', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
