# Generated by Django 6.0 on 2026-07-27 09:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0031_adminwithdrawal_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvitation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admininvitation',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'login'), ('LOGOUT', 'logout'), ('CREATE', 'create'), ('UPDATE', 'update'), ('DELETE', 'delete'), ('FAILED_LOGIN', 'failed_login')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='otp_secret',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adminwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='revenuejournal',
            name='balance_after',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revenuejournal',
            name='balance_before',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revenuejournal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
