# Generated by Django 5.2.5 on 2025-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='message',
            field=models.TextField(default='dddddd'),
            preserve_default=False,
        ),
    ]
