# Generated by Django 5.2.5 on 2025-11-05 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0003_alter_userticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
