# Generated by Django 5.2.5 on 2025-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0004_userticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
