# Generated by Django 5.2.5 on 2025-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
