# Generated by Django 5.2.5 on 2025-11-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserPanel', '0008_usertwofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
