# Generated by Django 5.2.5 on 2025-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0009_usertwofactor_is_verified'),
    ]

    operations = [

    ]
