# Generated by Django 5.2.5 on 2025-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0010_alter_usertwofactor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
