# Generated by Django 5.2.5 on 2025-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0011_alter_userticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
