# Generated by Django 5.2.5 on 2025-11-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0012_alter_userticket_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
