# Generated by Django 5.2.5 on 2025-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0013_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('answered', 'answered')], default='open', max_length=20),
        ),
    ]
