# Generated by Django 6.0 on 2026-02-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0016_notification_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
