# Generated by Django 6.0 on 2026-02-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0017_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
