# Generated by Django 6.0 on 2026-05-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0019_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
