# Generated by Django 6.0 on 2026-05-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0021_faqcategory_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
