# Generated by Django 5.2.5 on 2025-09-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
