# Generated by Django 5.2.5 on 2025-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileapprovalstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
