# Generated by Django 5.2.5 on 2025-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_profileapprovalstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileapprovalstatus',
            name='address_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_status', max_length=20),
        ),
        migrations.AddField(
            model_name='profileapprovalstatus',
            name='profile_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_status', max_length=20),
        ),
    ]
