# Generated by Django 5.2.5 on 2025-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_phone_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', editable=False, max_length=254, unique=True),
        ),
    ]
