# Generated by Django 5.2.5 on 2025-09-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
