# Generated by Django 5.2.5 on 2025-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_userprofile_city_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
    ]
