# Generated by Django 5.2.5 on 2025-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileapprovalstatus',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
