# Generated by Django 5.2.5 on 2025-09-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_profileapprovalstatus_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileapprovalstatus',
            name='locked',
        ),
    ]
