# Generated by Django 6.0 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_notification_admin_recipient_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ticket', 'Ticket System'), ('withdraw', 'Withdrawal Process'), ('deposit', 'Deposit System'), ('general', 'General Notification')], default='general', max_length=20),
        ),
    ]
