# Generated by Django 6.0 on 2026-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ticket', 'Ticket System'), ('withdraw', 'Withdrawal Process'), ('deposit', 'Deposit System'), ('kyc', 'KYC Verification'), ('general', 'General Notification')], default='general', max_length=20),
        ),
    ]
