# Generated by Django 6.0 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
