# Generated by Django 6.0 on 2026-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_userprofile_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
