# Generated by Django 6.0 on 2026-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_notification_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ticket', 'Ticket System'), ('withdraw', 'Withdrawal Process'), ('deposit', 'Deposit System'), ('kyc', 'KYC Verification'), ('general', 'General Notification')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
