# Generated by Django 6.0 on 2026-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_notification_category_alter_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
