# Generated by Django 6.0 on 2026-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_userprofile_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(blank=True, default='not_submitted', max_length=20),
        ),
    ]
