# Generated by Django 6.0 on 2026-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kyc_document',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='kyc_document_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='kyc_status',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
