# Generated by Django 6.0 on 2026-06-01 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_userprofile_ban_end_userprofile_ban_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_start', models.DateTimeField()),
                ('ban_end', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField()),
                ('unbanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ban_start'],
            },
        ),
    ]
