# Generated by Django 6.0 on 2026-06-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_userbanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbanhistory',
            name='ban_end',
        ),
    ]
