# Generated by Django 6.0 on 2026-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_userbanhistory_ban_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Custom Username'),
        ),
    ]
