# Generated by Django 6.0 on 2026-07-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
