# Generated by Django 6.0 on 2026-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileapprovalstatus',
            name='address_status',
        ),
        migrations.RemoveField(
            model_name='profileapprovalstatus',
            name='profile_status',
        ),
        migrations.AlterField(
            model_name='profileapprovalstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
