# Generated by Django 5.2.5 on 2025-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_code_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
