# Generated by Django 5.2.5 on 2025-10-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_last_code_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_code_sent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_expiry',
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
