# Generated by Django 5.2.5 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarwallet',
            name='private_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
