# Generated by Django 5.2.5 on 2025-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='pay_address',
            field=models.CharField(default='ccc', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_id',
            field=models.CharField(default='www', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='purchase_id',
            field=models.CharField(default='www', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
