# Generated by Django 5.2.5 on 2025-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallettransaction_pay_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
