# Generated by Django 5.2.5 on 2025-10-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallettransaction_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
