# Generated by Django 5.2.5 on 2025-10-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallettransaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollarwallet',
            name='currency',
            field=models.CharField(default='usdttrc20', max_length=20),
        ),
    ]
