# Generated by Django 5.2.5 on 2025-10-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_withdrawrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawrequest',
            old_name='address',
            new_name='target_address',
        ),
    ]
