# Generated by Django 5.2.5 on 2025-10-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_rename_address_withdrawrequest_target_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('Done', 'Done')], default='pending', max_length=20),
        ),
    ]

