# Generated by Django 5.2.5 on 2025-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallettransaction_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='pay_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
