# Generated by Django 5.2.5 on 2025-10-31 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_wallettransaction_pay_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.withdrawrequest'),
        ),
    ]
