# Generated by Django 5.2.5 on 2025-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_wallettransaction_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
