# Generated by Django 5.2.5 on 2025-11-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_withdrawrequest_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='withdraw_tx_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
