# Generated by Django 5.2.5 on 2025-11-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_wallettransaction_withdraw_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
