# Generated by Django 6.0 on 2026-02-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_alter_ticketreply_admin_sender'),
        ('wallet', '0017_dollarwallet_frozen_balance_withdrawrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin description', null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who approved or rejected this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='adminPanel.adminuser'),
        ),
    ]
