# Generated by Django 6.0 on 2026-02-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_alter_ticketreply_admin_sender'),
        ('wallet', '0018_withdrawrequest_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dollarwallet',
            options={'verbose_name': 'Dollar Wallet', 'verbose_name_plural': 'Dollar Wallets'},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.dollarwallet'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='adminPanel.adminuser'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
