# Generated by Django 6.0 on 2026-06-23 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_alter_dollarwallet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dollarwallet',
            options={'verbose_name': 'Crypto Wallet', 'verbose_name_plural': 'Crypto Wallets'},
        ),
        migrations.AlterField(
            model_name='dollarwallet',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dollarwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dollarwallet',
            unique_together={('user', 'currency')},
        ),
    ]
