# Generated by Django 6.0 on 2026-06-26 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_alter_dollarwallet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('usdttrc20', 'USDT (TRC-20)'), ('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('trx', 'Tron')], max_length=20, unique=True, verbose_name='کد ارز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('allow_auto_withdraw', models.BooleanField(default=True, verbose_name='اجازه برداشت خودکار')),
                ('auto_withdraw_limit', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='سقف واریز خودکار')),
                ('admin_review_limit', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='سقف بررسی امنیتی ادمین')),
            ],
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='withdraw_tx_hash',
        ),
        migrations.AlterField(
            model_name='dollarwallet',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dollarwallet',
            name='frozen_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
    ]
