# Generated by Django 6.0 on 2026-07-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_currencyconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
