# Generated by Django 6.0 on 2026-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_withdrawrequest_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconfig',
            name='fee_structure',
            field=models.JSONField(default=dict, verbose_name='ساختار کارمزد (JSON)'),
        ),
    ]
