# Generated by Django 6.0 on 2026-07-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_currencyconfig_fee_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dollarwallet',
            options={'ordering': ['currency'], 'verbose_name': 'Crypto Wallet', 'verbose_name_plural': 'Crypto Wallets'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
